### ISSUE TITLE
Fatal error: Unable to bridge NSNumber to UInt64

### ISSUE THREAD

**Issue by Fanom2813** [Sunil9162/flutter_thermal_printer#12]
2024-11-10 08:15:17.946 mep_desktop[77229:3827728] [FBP-iOS] handleMethodCall: setLogLevel
Foundation/NSNumber.swift:341: Fatal error: Unable to bridge NSNumber to UInt64
Lost connection to device.

hi, i get the above error when initializing the plugin

**Comment by lazicah** [comment]
Any solution to this?

**Comment by Sunil9162** [comment]
Is this from this package.

If you are using macos it is not for macos right now for usb only works with bluetooth on macos
