### ISSUE TITLE
Getting null exception while print widget

### ISSUE THREAD

**Issue by Aruljebaraj** [Sunil9162/flutter_thermal_printer#15]
Tried to print widget 
<img width="771" alt="Screenshot 2024-12-10 at 1 08 22 pm" src="https://github.com/user-attachments/assets/c77cc711-b25a-4308-8b95-27baf2b98c9a">
<img width="978" alt="Screenshot 2024-12-10 at 1 08 43 pm" src="https://github.com/user-attachments/assets/108359ed-7691-4035-84ee-6418d3bf0530">

eg:
                        await _flutterThermalPrinterPlugin.printWidget(
                          context,
                          widget: Image.memory(bytes,height: 100,width: 100,),
                          printer: printers[index],
                          printOnBle: true,delay: const Duration(seconds: 10)
                        );

 eg: await _flutterThermalPrinterPlugin.printWidget(
                          context,
                          widget:Text('sgsvvh'),
                          printer: printers[index],
                          printOnBle: true,delay: const Duration(seconds: 10)
                        );

**Comment by Sunil9162** [comment]
Hii @Aruljebaraj 

The issue has been fixed. Please update the package.

Thanks

**Comment by Aruljebaraj** [comment]
@Sunil9162  print widget isn't working  await _flutterThermalPrinterPlugin.printWidget(
context,
widget:Text('sgsvvh'),
printer: printers[index],
printOnBle: true,delay: const Duration(seconds: 10)
);
![image](https://github.com/user-attachments/assets/3c595491-5336-4144-9c7c-7c03a8059992)

**Comment by Sunil9162** [comment]
Which Version you are using

**Comment by Aruljebaraj** [comment]
version flutter_thermal_printer: ^1.0.1
