### ISSUE TITLE
Please add condition when running flutter web

### ISSUE THREAD

**Issue by skylastn** [Sunil9162/flutter_thermal_printer#16]
/C:/Users/sahid/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_thermal_printer-0.0.19+1/lib/Windows/print_data.dart:6:8: Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
Context: The unavailable library 'dart:ffi' is imported through these packages:

    web_entrypoint.dart => package:my_food_app => package:flutter_thermal_printer => package:ffi => dart:ffi
    web_entrypoint.dart => package:my_food_app => package:flutter_thermal_printer => package:win32 => dart:ffi
    web_entrypoint.dart => package:my_food_app => package:flutter_thermal_printer => package:win32 => package:ffi => dart:ffi
    ...

Detailed import paths for (some of) the these imports:

**Comment by Sunil9162** [comment]
Sure will be there in next update meanwhile if you don't want it on web just don't create instance of Flutter_thermal_printer or use

```dart
kWeb

```

Thanks
