### ISSUE TITLE
[HELP] It's not working

### ISSUE THREAD

**Issue by habibi-bfi** [Sunil9162/flutter_thermal_printer#18]
Hi, I'm trying to print with my USB thermal printer. I have already implemented as the example.
1. `[ok]` Get printer list with `StreamSubscription<List<Printer>>? _devicesStreamSubscription;`
2. `[ok]` Check the connected printer with `.isConnected` 
3. `[ok]` Otherwise, connect the printer with `.connect(selectedPrinter)`
4. `[failed]`Try to print with this command (with `try and catch`):
```
final profile = await CapabilityProfile.load();
final generator = Generator(PaperSize.mm58, profile);
List<int> bytes = [];
bytes += generator.text(
 'Test Print Text',
 styles: const PosStyles(
  bold: true,
  height: PosTextSize.size3,
  width: PosTextSize.size3,
 ),
);
bytes += generator.cut();
await flutterThermalPrinterPlugin.printData(connectedPrinter, bytes);
```

And it's just sit there and do nothing, not even throw any error. What could be wrong?

Thanks

**Comment by Sunil9162** [comment]
```dart
final profile = await CapabilityProfile.load();
final generator = Generator(PaperSize.mm80, profile);
List<int> bytes = [];
bytes += generator.text(
  "Test Prin",
  styles: const PosStyles(
    bold: true,
    height: PosTextSize.size3,
    width: PosTextSize.size3,
  ),
);
bytes += generator.cut();
await _flutterThermalPrinterPlugin.printData(
  printers[index],
  bytes,
  longData: true,
);
```

Try Using longData to true so that i can print fast. If not worked please reopen the issue.

Thanks
