### ISSUE TITLE
error printing images

### ISSUE THREAD

**Issue by Sor0** [Sunil9162/flutter_thermal_printer#2]
i'm trying to use this library to print a tick, but i need to print an image, i was testing to print text and it worked as well but if i try to print an image it doesn't work, doesn't show any error message simply don't print anything

here is an example of the code:
```dart
printTicket(FlutterThermalPrinter printerPlugin, Printer printer) async {
  final profile = await CapabilityProfile.load();
  final generator = Generator(PaperSize.mm80, profile);
  List<int> bytes = [];
  final byteData = await rootBundle.load('assets/images/image.png');
  bytes += generator.text('Test text',
      styles: const PosStyles(
        bold: true,
        height: PosTextSize.size3,
        width: PosTextSize.size3,
      ));
  final img = decodeImage(byteData.buffer.asUint8List());
  if (img != null) {
    bytes += generator.image(img);
  }
  bytes += generator.cut();
  await printerPlugin.printData(printer, bytes, longData: true);
}
```

**Comment by SuniliByte** [comment]
Can you give a try to this code

` final imagebytes = await img.decodeImage(image);
    final totalheight = imagebytes!.height;
    final totalwidth = imagebytes.width;
    final timestoCut = totalheight ~/ 30;
    for (var i = 0; i < timestoCut; i++) {
      final croppedImage = img.copyCrop(
        imagebytes,
        x: 0,
        y: i * 30,
        width: totalwidth,
        height: 30,
      );
      final raster = ticket.imageRaster(croppedImage);
      await FlutterThermalPrinter.instance.printData(
        printer!,
        raster,
        longData: true,
      );
    }
    await FlutterThermalPrinter.instance.printData(
      printer!,
      ticket.cut(),
      longData: true,
    );`

Crop the long image into smaller sizes so that it can print faster
