### ISSUE TITLE
IOS Error - The app tries to turn on bluetooth on start of the application. But IOS doesn't allow turning on the bluetooth via app.

### ISSUE THREAD

**Issue by nirmal-kc** [Sunil9162/flutter_thermal_printer#21]
Start the app with Bluetooth already turned on, we get the below mentioned error and the scan device operation doesn't return anything. Just keeps throwing the error.
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(turnOn, iOS does not support turning on bluetooth, null, null)`

Now turn off and turn on the bluetooth, the app starts working. The error is due to the below mentioned code, from other_printers_manager.dart. 

`if (FlutterBluePlus.adapterStateNow != BluetoothAdapterState.on) {
        await FlutterBluePlus.turnOn();
}`

Adding a check if the platform is not IOS resolves this issue.

`if ((FlutterBluePlus.adapterStateNow != BluetoothAdapterState.on) &&
          !Platform.isIOS) {
        await FlutterBluePlus.turnOn();
      }`

Let me know if you need more info. Thanks.

**Comment by nirmal-kc** [comment]
That's because on IOS, the state always starts with BluetoothAdapterState.unknown. This is mentioned in the flutter_blue_plus package. 

```
adapterState is not 'on' but my Bluetooth is on 
For iOS:

adapterState always starts as unknown. You need to wait longer for the service to initialize. As simple as:

if (FlutterBluePlus.adapterStateNow == BluetoothAdapterState.unknown) {
    await Future.delayed(const Duration(seconds: 1));
}
```

And we also need to gracefully handle any errors, for example prompt user that the bluetooth is turned off and user needs to manually turn it on.

**Comment by Sunil9162** [comment]
Hello @nirmal-kc ,

Thanks for addressing the issue will update it soon.
