### ISSUE TITLE
missing plugin exception after running it on flutter windows

### ISSUE THREAD

**Issue by samih93** [Sunil9162/flutter_thermal_printer#3]
Unhandled Exception: MissingPluginException(No implementation found for method flutterHotRestart on channel flutter_blue_plus/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>

**Comment by SuniliByte** [comment]
Currently on Windows it not supporting. We are developing it so that it can support all platforms.
