### ISSUE TITLE
Issue with Garbled Characters After Paper Runs Out During Printing

### ISSUE THREAD

**Issue by iOSyan** [Sunil9162/flutter_thermal_printer#8]
Great library, thank you so much! 
However, I've encountered an issue. When my printer runs out of paper, but the image content hasn't been fully printed, the next time I print, garbled characters appear. Is there a solution for this? I have already sent a reset command before printing. My connection method is BLE.

**Comment by Sunil9162** [comment]
Hello,

Great to heare that it helps you. Let me check the same and will update you soon.

Thanks
